{% set name = "normaliz" %}
{% set version = "3.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Normaliz/Normaliz/releases/download/v{{ version }}/normaliz-{{ version }}-full.zip
  sha256: 48b9c4b76e4c5dcab3c7845e98d889a45869fa14b4ff23cae003e5c617f08b3b

build:
  number: 2
  skip: True  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage("normaliz") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp          # [osx]
    - posix                # [win]
    - clangdev             # [win]
    - lld                  # [win]
    - llvmdev              # [win]
    - m2-automake-wrapper  # [win]
    - m2-libtool           # [win]
    - m2-autoconf          # [win]
    - m2-make              # [win]
    - m2-m4                # [win]
    - autoconf             # [not win]
    - automake             # [not win]
    - libtool              # [not win]
  host:
    - libflint             # [not win]
    - boost-cpp
    - gmp                  # [not win]
    - mpir                 # [win]
    - llvm-openmp          # [osx]
    - e-antic              # [not win]
    - nauty
  run:
    - llvm-openmp          # [osx]

test:
  commands:
    - test -f "$PREFIX/lib/libnormaliz.a"                       # [not win]
    - test -f "$PREFIX/lib/libnormaliz${SHLIB_EXT}"             # [not win]
    - test -f "$PREFIX/include/libnormaliz/matrix.h"            # [not win]
    - if not exist %LIBRARY_LIB%\\normaliz.lib exit 1         # [win]
    - if not exist %LIBRARY_LIB%\\normaliz_static.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\normaliz\\matrix.h exit 1   # [win]

about:
  home: https://www.normaliz.uni-osnabrueck.de
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: ' Normaliz is an open source tool for computations in affine monoids, vector configurations, lattice polytopes, and rational cones.'
  dev_url: https://github.com/Normaliz/Normaliz

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
