{% set name = "normaliz" %}
{% set version = "3.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Normaliz/Normaliz/releases/download/v{{ version }}/normaliz-{{ version }}-full.zip
  sha256: 48b9c4b76e4c5dcab3c7845e98d889a45869fa14b4ff23cae003e5c617f08b3b

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libflint
    - boost-cpp
    - gmp
  run:
    - gmp
    - {{ pin_compatible("libflint", max_pin="x.x") }}

test:
  commands:
    - test -f "$PREFIX/lib/libnormaliz.a"
    - test -f "$PREFIX/lib/libnormaliz${SHLIB_EXT}"
    - test -f "$PREFIX/include/libnormaliz/matrix.h"

about:
  home: https://www.normaliz.uni-osnabrueck.de
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: ' Normaliz is an open source tool for computations in affine monoids, vector configurations, lattice polytopes, and rational cones.'
  dev_url: https://github.com/Normaliz/Normaliz

extra:
  recipe-maintainers:
    - isuruf
